import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';

class ChatMessage {
  final String id;
  final String username;
  final String message;
  final DateTime timestamp;
  final bool isAdmin;

  ChatMessage({
    required this.id,
    required this.username,
    required this.message,
    required this.timestamp,
    required this.isAdmin,
  });

  factory ChatMessage.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return ChatMessage(
      id: doc.id,
      username: data['username'] ?? 'Unknown',
      message: data['message'] ?? '',
      timestamp: (data['timestamp'] as Timestamp).toDate(),
      isAdmin: data['isAdmin'] ?? false,
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'username': username,
      'message': message,
      'timestamp': Timestamp.fromDate(timestamp),
      'isAdmin': isAdmin,
    };
  }
}

class ChatService {
  static final ChatService _instance = ChatService._internal();
  factory ChatService() => _instance;
  ChatService._internal();

  final CollectionReference _messagesCollection = 
      FirebaseFirestore.instance.collection('community_chat_messages');

  // Send a message to the chat
  Future<void> sendMessage({
    required String username,
    required String message,
    bool isAdmin = false,
  }) async {
    try {
      final chatMessage = ChatMessage(
        id: '', // Will be generated by Firestore
        username: username,
        message: message,
        timestamp: DateTime.now(),
        isAdmin: isAdmin,
      );

      await _messagesCollection.add(chatMessage.toFirestore());
    } catch (e) {
      print('Error sending message: $e');
      rethrow;
    }
  }

  // Get real-time stream of messages
  Stream<List<ChatMessage>> getMessagesStream() {
    return _messagesCollection
        .orderBy('timestamp', descending: false)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => ChatMessage.fromFirestore(doc))
          .toList();
    });
  }

  // Get recent messages (one-time fetch)
  Future<List<ChatMessage>> getRecentMessages({int limit = 50}) async {
    try {
      final snapshot = await _messagesCollection
          .orderBy('timestamp', descending: false)
          .limit(limit)
          .get();
      
      return snapshot.docs
          .map((doc) => ChatMessage.fromFirestore(doc))
          .toList();
    } catch (e) {
      print('Error fetching messages: $e');
      return [];
    }
  }

  // Delete old messages (cleanup)
  Future<void> deleteOldMessages({int keepCount = 100}) async {
    try {
      final snapshot = await _messagesCollection
          .orderBy('timestamp', descending: false)
          .get();
      
      if (snapshot.docs.length > keepCount) {
        final docsToDelete = snapshot.docs
            .take(snapshot.docs.length - keepCount)
            .toList();
        
        final batch = FirebaseFirestore.instance.batch();
        for (final doc in docsToDelete) {
          batch.delete(doc.reference);
        }
        
        await batch.commit();
      }
    } catch (e) {
      print('Error deleting old messages: $e');
    }
  }

  // Reset entire chat (admin only)
  Future<void> resetChat() async {
    try {
      final snapshot = await _messagesCollection.get();
      
      final batch = FirebaseFirestore.instance.batch();
      for (final doc in snapshot.docs) {
        batch.delete(doc.reference);
      }
      
      await batch.commit();
      
      // Add welcome message after reset
      await sendMessage(
        username: 'admin',
        message: 'Chat has been reset. Welcome to the fresh sWorld Community Chat! 🌍',
        isAdmin: true,
      );
    } catch (e) {
      print('Error resetting chat: $e');
      rethrow;
    }
  }

  // Initialize chat with welcome message if empty
  Future<void> initializeChat() async {
    try {
      final snapshot = await _messagesCollection.limit(1).get();
      
      if (snapshot.docs.isEmpty) {
        // Add welcome message from admin
        await sendMessage(
          username: 'admin',
          message: 'Welcome to the sWorld Community Chat! 🌍',
          isAdmin: true,
        );
      }
    } catch (e) {
      print('Error initializing chat: $e');
    }
  }
}
