// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApxJ92BetzBvzDNzHW60hV7RWGNuABlk0',
    appId: '1:84474909213:web:98a9a23f86bc5f2cbe6cf4',
    messagingSenderId: '84474909213',
    projectId: 'sworld-9807c',
    authDomain: 'sworld-9807c.firebaseapp.com',
    databaseURL: 'https://sworld-9807c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sworld-9807c.firebasestorage.app',
    measurementId: 'G-568FTJ4GNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOo4-pAw7pYScJ5wsrOu01JjjSeT27h-4',
    appId: '1:84474909213:android:20232a620196fabbbe6cf4',
    messagingSenderId: '84474909213',
    projectId: 'sworld-9807c',
    databaseURL: 'https://sworld-9807c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sworld-9807c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACqYYZ1UXgo23t2OHUCOHek7Qi0nLtV0U',
    appId: '1:84474909213:ios:100158449caf6a5abe6cf4',
    messagingSenderId: '84474909213',
    projectId: 'sworld-9807c',
    databaseURL: 'https://sworld-9807c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sworld-9807c.firebasestorage.app',
    iosClientId: '84474909213-iuqe3gjk87rveauv2vpo7cdchcp77le8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACqYYZ1UXgo23t2OHUCOHek7Qi0nLtV0U',
    appId: '1:84474909213:ios:100158449caf6a5abe6cf4',
    messagingSenderId: '84474909213',
    projectId: 'sworld-9807c',
    databaseURL: 'https://sworld-9807c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sworld-9807c.firebasestorage.app',
    iosClientId: '84474909213-iuqe3gjk87rveauv2vpo7cdchcp77le8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApxJ92BetzBvzDNzHW60hV7RWGNuABlk0',
    appId: '1:84474909213:web:9606d78cf309605dbe6cf4',
    messagingSenderId: '84474909213',
    projectId: 'sworld-9807c',
    authDomain: 'sworld-9807c.firebaseapp.com',
    databaseURL: 'https://sworld-9807c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sworld-9807c.firebasestorage.app',
    measurementId: 'G-XH9CE0K2GW',
  );
}
